CREATE TABLE IF NOT EXISTS `r_tasks` (
	`id` BINARY(16) NOT NULL COMMENT 'id',
	`title` VARCHAR(255) NOT NULL,
	`detail` TEXT NULL,
	`completed` BOOLEAN NOT NULL,
	`deadline` DATE NULL,
	`created_by` BINARY(16) NOT NULL,
	`created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	`updated_by` BINARY(16) NOT NULL,
	`updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
	`version` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID())),
	PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `e_task_events` (
  `id` BINARY(16) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `task_id` BINARY(16) NOT NULL,
  `data` JSON NOT NULL,
  `created_by` BINARY(16) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
