CREATE TABLE IF NOT EXISTS `m_task_event_types` (
    `id` BINARY(16) NOT NULL COMMENT 'タスクイベントタイプID',
    `name` VARCHAR(255) NOT NULL COMMENT 'タスクイベント名',
    `register_by` BINARY(16) NOT NULL COMMENT '登録者',
    `register_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '登録日時',
    `updated_by` BINARY(16) NOT NULL COMMENT '更新者',
    `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新日時',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT='タスクイベントタイプ';
